#!/usr/bin/env bash

File="${XDG_CONFIG_HOME:-$HOME/.config}"/X11/Xresources

while read -r; do
	case $REPLY in
		*size=15.5*)
			Data+=("${REPLY/15.5/30.5}") ;;

		*size=30.5*)
			Data+=("${REPLY/30.5/15.5}") ;;

		*)
			Data+=("$REPLY") ;;
	esac
done < "$File"

printf '%s\n' "${Data[@]}" > "$File"
xrdb "$File"
