#!/usr/bin/env bash

File="${XDG_CONFIG_HOME:-$HOME/.config}"/X11/Xresources
Content=$(< "$File")

while read Font; do
	[[ "$Font" == 'URxvt*.font:'* ]] && break
done < "$File"

case $Font in
	*15.5*)
		while read; do
			if [[ $REPLY == 'URxvt*.font:'* ]]; then
				REPLY="${REPLY/15.5/30.5}"
			fi
			printf '%s\n' "$REPLY"
		done <<< "$Content" > "$File" ;;

	*30.5*)
		while read; do
			if [[ $REPLY == 'URxvt*.font:'* ]]; then
				REPLY="${REPLY/30.5/15.5}"
			fi
			printf '%s\n' "$REPLY"
		done <<< "$Content" > "$File" ;;
esac

xrdb "$File"
