#!/usr/bin/env bash

file=${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources

while read -r; do
	case $REPLY in
		*size=15.5*)
			data+=("${REPLY/15.5/30.5}") ;;

		*size=30.5*)
			data+=("${REPLY/30.5/15.5}") ;;

		*)
			data+=("$REPLY") ;;
	esac
done < "$file"

printf '%s\n' "${data[@]}" > "$file"
xrdb "$file"
