#!/usr/bin/env bash

Perm="$(ls -ld $1 | awk '{print $1}')"; Perm="${Perm#?}"
Owner="${Perm%??????}"
Group="${Perm#???}"; Group="${Group%???}"
Other="${Perm#??????}"

case "$Owner" in
  '---')
    u=0 ;;
  '--x')
    u=1 ;;
  '-w-')
    u=2 ;;
  '-wx')
    u=3 ;;
  'r--')
    u=4 ;;
  'r-x')
    u=5 ;;
  'rw-')
    u=6 ;;
  'rwx')
    u=7 ;;
esac

case "$Group" in
  '---')
    g=0 ;;
  '--x')
    g=1 ;;
  '-w-')
    g=2 ;;
  '-wx')
    g=3 ;;
  'r--')
    g=4 ;;
  'r-x')
    g=5 ;;
  'rw-')
    g=6 ;;
  'rwx')
    g=7 ;;
esac

case "$Other" in
  '---')
    o=0 ;;
  '--x')
    o=1 ;;
  '-w-')
    o=2 ;;
  '-wx')
    o=3 ;;
  'r--')
    o=4 ;;
  'r-x')
    o=5 ;;
  'rw-')
    o=6 ;;
  'rwx')
    o=7 ;;
esac

DefPerm="${u}${g}${o}"

printf "$DefPerm\n"
