#!/bin/sh

while read line; do
	case $line in
		*xkb_symbols*)
			break ;;
	esac
done <<-EOF
	`setxkbmap -print`
EOF

IFS='+' read _ keymap _ <<-EOF
	$line
EOF

case $keymap in
	us*)
		setxkbmap th
		dunstify -u low -r 71 'Keymap: th' ;;
	*)
		setxkbmap us grammak_iso
		dunstify -u low -r 71 'Keymap: us(grammak_iso)' ;;
esac
