#!/bin/sh

while read Curline; do
	case "$Curline" in
		*xkb_symbols*)
			break ;;
	esac
done <<-EOF
	`setxkbmap -print`
EOF

IFS='+' read F1 Keymap _ <<-EOF
	$Curline
EOF

case "$Keymap" in
	us*)
		setxkbmap th -option shift:both_capslock
		xmodmap -e 'clear Lock' \
			-e 'keycode 66 = Control_L' \
			-e 'add Control = Control_L' ;;
	*)
		setxkbmap us -variant colemak_dhk \
			-option ctrl:nocaps \
			-option shift:both_capslock ;;
esac

killall xcape
xcape -e 'Control_L=Escape'
