#!/bin/sh

key(){
	setxkbmap -print | grep 'xkb_symbols' | \
		awk '{print $4}' | awk -F + '{print $2}'
}

case $(key) in
	'us(colemak)')
		setxkbmap th ;;
	*)
		setxkbmap us -variant colemak ;;
esac
