#!/bin/sh

if test -z "$1"; then
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	case `pactl get-sink-mute @DEFAULT_SINK@` in
		*no) Volume=Unmuted ;;
		*yes) Volume=Muted ;;
	esac
else
	pactl set-sink-volume @DEFAULT_SINK@ "$@"
	read F1 F2 F3 F4 Volume _ <<-EOF
		`pactl get-sink-volume @DEFAULT_SINK@`
	EOF
fi

dunstify -u low -r 101 "Volume: $Volume"
