#!/usr/bin/env bash

trap 'unset File Word Meaning Exist' EXIT

File="$HOME/.local/share/dictionary"

[ -f "$File" ] || touch $File

Word=$(sed 's/ - .*//' $File | rofi -dmenu -i -p 'Word')

[ -z "$Word" ] && exit

Exist=$(grep -Eio "^$Word" $File)

if [ -z "$Exist" ]; then

	Meaning=$(rofi -dmenu -p 'Meaning')
	[ -z "$Meaning" ] && exit

	echo "$Word - $Meaning" >> $File
else
	grep -Ei "^$Word" $File | rofi -dmenu -i -p 'Matching'
fi
