#!/usr/bin/env bash

trap 'unset Options Options' EXIT

Options=(
	'Entire screen'
	'Choose specific window'
	'Focused window'
)

Option="$(printf '%s\n' "${options[@]}" | rofi -dmenu -p 'Screenshot')"

[ -z "$Option" ] && exit

case "$Option" in
	'Entire screen')
		scrot -q 100 '%Y-%m-%d_%H:%M:%S.png' -e 'mv $f ~/Pictures/' ;;
	'Choose specific window')
		scrot -s -q 100 '%Y-%m-%d_%H:%M:%S.png' -e 'mv $f ~/Pictures/' ;;
	'Focused window')
		scrot -u -q 100 '%Y-%m-%d_%H:%M:%S.png' -e 'mv $f ~/Pictures/' ;;
	*) ;;
esac
