#!/bin/sh

File="$HOME/.local/share/dictionary"

test -f "$File" || printf '' > $File

Word=$(while read -r CurLine; do printf '%s\n' "${CurLine% -*}"; done < $File \
	| rofi -dmenu -i -p 'Word: ')

test -z "$Word" && exit

if test -z "$(grep -io "^$Word" $File)"; then

	Meaning=$(rofi -dmenu -p 'Meaning: ')
	test -z "$Meaning" && exit

	echo "$Word - $Meaning" >> $File
else
	grep -i "^$Word" $File | rofi -dmenu -i -p 'Matching: '
fi
