#!/bin/sh

dmenu() { rofi -dmenu "$@"; }

File="${XDG_DATA_HOME:-$HOME/.local/share}"/dictionary

test -f "$File" || printf '' > "$File"

findword() {
	while IFS=' - ' read Curline _; do
		printf '%s\n' "$Curline"
	done < "$File"
	unset -v Curline
}

Word=$(findword | dmenu -i -p 'Word')

test -z "$Word" && exit 0

List=$(grep -i ^"$Word" "$File")

if test -n "$List"; then
	echo "$List" | dmenu -i -p 'Matching'
else
	Meaning=$(dmenu -i -p 'Meaning')
	test -z "$Meaning" && exit 0
	echo "$Word - $Meaning" >> "$File"
fi
