#!/usr/bin/env bash

rmenu() { rofi -dmenu -i -p 'Screenshot'; }

Options=(
	'Full Screen'
	'Focused Window'
	'Choose Specific Area/Window'
)

[[ -z $Choice ]] && Choice=$(printf '%s\n' "${Options[@]}" | rmenu)

[[ -z $Choice ]] && exit 0

ss() {
	local Dest="$HOME/Pictures/$(printf '%(%F_%T)T').png"
	if maim "$@" "$Dest"; then
		dunstify -u low -i "$Dest" 'Captured Successfully...'
	else
		dunstify -u low 'Failed to Capture...'
	fi
}

case "$Choice" in
	"${Options[0]}")
		ss ;;

	"${Options[1]}")
		ss -i "$(xdotool getactivewindow)" ;;

	"${Options[2]}")
		ss -s ;;
esac
