#!/bin/sh

Choice=$(printf '%s\n' \
	'Entire screen' \
	'Choose specific window' \
	'Focused window' \
	| rofi -dmenu -i -p 'Screenshot')

test -z "$Choice" && exit

Screenshot() {
	scrot "$@" -q 100 '%Y-%m-%d_%H:%M:%S.png' -e 'mv $f ~/Pictures/'
}

case "$Choice" in
	'Entire screen')
		Screenshot ;;
	'Choose specific window')
		Screenshot -s ;;
	'Focused window')
		Screenshot -u ;;
esac
