#!/usr/bin/env bash

Options=(
	'Entire screen'
	'Choose specific window'
	'Focused window'
)

Option=$(printf '%s\n' "${Options[@]}" | rofi -dmenu -i -p 'Screenshot')

[ -z "$Option" ] && exit

Screenshot(){
	scrot "$@" -q 100 '%Y-%m-%d_%H:%M:%S.png' -e 'mv $f ~/Pictures/'
}

case "$Option" in
	'Entire screen')
		Screenshot ;;
	'Choose specific window')
		Screenshot -s ;;
	'Focused window')
		Screenshot -u ;;
esac
