#!/usr/bin/env bash

Options=(
	'Entire screen'
	'Choose specific window'
	'Focused window'
)

Option=$(printf '%s\n' "${Options[@]}" | rofi -dmenu -i -p 'Screenshot')

[ -z "$Option" ] && exit

case "$Option" in
	'Entire screen')
		scrot -q 100 '%Y-%m-%d_%H:%M:%S.png' -e 'mv $f ~/pix/' ;;
	'Choose specific window')
		scrot -s -q 100 '%Y-%m-%d_%H:%M:%S.png' -e 'mv $f ~/pix/' ;;
	'Focused window')
		scrot -u -q 100 '%Y-%m-%d_%H:%M:%S.png' -e 'mv $f ~/pix/' ;;
esac
