#!/usr/bin/env bash

# Dependencies):
#   coreutils (bash, ls)
#   curl (Upload utility)
#   dmenu/rofi (Default run menu)
#   xclip (Clipboard support)
#   dunst (dunstify)
#   notify-send (dunstify)

if ! type -P dmenu &>/dev/null; then
	dmenu() { rofi -dmenu "$@"; }
fi

log=${XDG_DATA_HOME:-$HOME/.local/share}/0x0.log

[[ -d $XDG_DATA_HOME ]] || mkdir -p -- "$XDG_DATA_HOME"
[[ -f $log ]] || > "$log"

entry=(
	'Upload a File'
	'Recent Upload(s)'
)

select=$(printf '%s\n' "${entry[@]}" | dmenu -i -p 'Select')

case $select in
	${entry[0]})
		list() {
			echo ..
			command ls -ALNpX1 --group-directories-first
		}

		while :; do
			select=$(list | dmenu -i -p "$PWD")
			[[ -z $select ]] && exit 0

			if [[ -f $select ]]; then
				if ! url=$(curl -sF file=@"$select" https://0x0.st); then
					dunstify -u critical -- 'Error:' 'Failed to Upload'
					exit 1
				fi

				printf '%s' "$url" | xclip -sel c
				printf '%s' "$url" | xclip -sel p

				dunstify -u low -- 'File Uploaded' "URL: $url"
				echo "$(printf '%(%F_%T)T') $url $select" >> "$log"

				exit 0
			elif [[ -d $select ]]; then
				if ! cd -- "$select"; then
					dunstify -u normal -- 'Error:' 'The Directory not Readable'
				fi
			else
				dunstify -u normal -- 'Error:' 'Wrong File Type'
				exit 1
			fi
		done ;;

	${entry[1]})
		while read -r; do
			data=("$REPLY" "${data[@]}")
		done < "$log"

		read _ url _ <<< "$(printf '%s\n' "${data[@]}" | dmenu -i -p 'Select')"
		[[ -z $url ]] && exit 0

		printf '%s' "$url" | xclip -sel c
		printf '%s' "$url" | xclip -sel p

		dunstify -u low -- 'Copied to Clipboard' "URL: $url" ;;
esac
