#!/usr/bin/env bash

Dir=/media/ides3rt/USB1p2/GitHub/repositories

[ -d "$Dir" ] ||
	{ printf '%s\n' "ERR: $Dir doesn't exists.." 1>&2; exit 1 ;}

Repositories=(
	'Code' 'config' 'Documents' 'doasedit'
	'dotfiles' 'firefox' 'gists' 'librewolf'
	'Pictures' 'exit'
)

Count=$(wc -w <<< "${Repositories[@]}")

PS3="Select your repository [1-$Count]: "

select Repository in ${Repositories[@]}; do
	case "$Repository" in
		exit)
			break ;;

		gists)
			cp $HOME/GitHub/gists/* /media/ides3rt/USB1p2/GitHub/gists/ ;;

		*)
			if [ -n "$Repository" ]; then

				DDir="$Dir/$Repository"
				[ -d "$DDir" ] && rm -rf $DDir

				URL="https://github.com/ides3rt/$Repository"

				git clone -q "$URL" "$DDir" ||
					printf '%s\n' "$Repository doesn't exists..."
			fi ;;

	esac
done
