#!/usr/bin/env bash

trap 'sync' EXIT

Dir=/media/ides3rt/USB1p2/GitHub/repositories

[[ -d "$Dir" ]] ||
	{ printf '%s\n' "ERR: $Dir doesn't exists.." 1>&2; exit 1 ;}

Repositories=(
	'Code' 'config' 'Documents' 'doasedit'
	'dotfiles' 'firefox' 'gists' 'librewolf'
	'Pictures' 'exit'
)

Count=${#Repositories[@]}

PS3="Select your repository [1-$Count]: "

select Repository in ${Repositories[@]}; do
	[[ -z $Repository ]] && continue
	case "$Repository" in
		exit)
			exit 0 ;;

		gists)
			cp $HOME/GitHub/gists/* /media/ides3rt/USB1p2/GitHub/gists/ ;;

		*)
			DDir="$Dir/$Repository"
			[[ -d "$DDir" ]] && rm -rf $DDir

			URL="https://github.com/ides3rt/$Repository"

			git clone -q "$URL" "$DDir" ||
				printf '%s\n' "$Repository doesn't exists..." ;;

	esac
done
