#!/usr/bin/env bash

Permissions=$(ls -ld $1 | awk '{print $1}')
Permissions="${Permissions#?}"

Owner="${Permissions%??????}"

Group="${Permissions#???}"
Group="${Group%???}"

Others="${Permissions#??????}"

All=(
	"$Owner"
	"$Group"
	"$Others"
)

Permissions=
for Permission in ${All[@]}; do
	case "$Permission" in
		'---')
			Permission=0 ;;
		'--x')
			Permission=1 ;;
		'-w-')
			Permission=2 ;;
		'-wx')
			Permission=3 ;;
		'r--')
			Permission=4 ;;
		'r-x')
			Permission=5 ;;
		'rw-')
			Permission=6 ;;
		'rwx')
			Permission=7 ;;
	esac
	Permissions+="$Permission"
done

printf '%s\n' "$Permissions"
