#!/usr/bin/env bash

progrm=${0##*/}

panic() {
	printf '%s\n' "$progrm: $2" 1>&2
	(( $1 > 0 )) && exit $1
}

while [[ -n $1 ]]; do
	case $1 in
		-h|--help)
			read -d '' <<-EOF
				Usage: $progrm [OPTIONS] [GLOB]

				  -h, --help        - Display this help infomation.
				  -r, --raw         - Show tarball's full name.
				  -d, --dups        - Only show duplicate tarballs.

			EOF

			printf '%s' "$REPLY"
			exit 0 ;;

		-r|--raw)
			raw=true ;;

		-d|--dups)
			dups=true ;;

		--)
			shift
			break ;;

		-*)
			panic 1 "$1: invaild option..." ;;

		*)
			break ;;
	esac
	shift
done

count=1

for file in /var/cache/pacman/pkg/"$1"*.tar.zst; {
	[[ -f $file ]] || exit 1

	name=${file#/var/cache/pacman/pkg/}
	name=${name/-[0-9]*}

	if [[ $name == $old_name ]]; then
		(( count++ ))
		if [[ $dups == true && $raw == true ]]; then
			msg=${old_file:-$file}
			(( count > 1 )) && printf '%s\n' "$msg"
		fi
	else
		if [[ $raw == true ]]; then
			msg=${old_file:-$file}
		else
			msg="${old_name:-$name} - has $count tarball(s)."
		fi

		if [[ $dups == true ]]; then
			(( Count > 1 )) && printf '%s\n' "$msg"
		else
			printf '%s\n' "$msg"
		fi

		count=1
	fi

	old_file=$file
	old_name=$name
}
