#!/usr/bin/env bash

disk=$(lsblk -nso PATH "$(findmnt -nvo SOURCE /)" | tail -n 1)

if [[ $disk == /dev/nvme* ]]; then
	readonly disk=${disk%p*}
else
	readonly disk=${disk%%[1-9]}
fi

efibootmgr --disk "$disk" --part 1 --create \
	--label 'Arch Linux' \
	--loader '\EFI\ARCHX64\linux-hardened.efi'
