#!/usr/bin/env bash

Disk=$(lsblk -nso PATH "$(findmnt -nvo SOURCE /)" | tail -n 1)

if [[ $Disk == *nvme* ]]; then
	Disk="${Disk/p*}"
else
	Disk="${Disk/[1-9]*}"
fi

efibootmgr --disk "$Disk" --part 1 --create \
	--label 'Arch Linux' \
	--loader '\EFI\ARCHX64\linux-hardened.efi'
