#!/usr/bin/env bash

disk=$(lsblk -nso PATH "$(findmnt -nvo SOURCE /)" | tail -n 1)

if [[ $Disk == *nvme* ]]; then
	disk=${disk%p*}
else
	disk=${disk%%[1-9]}
fi

efibootmgr --disk "$disk" --part 1 --create \
	--label 'Arch Linux' \
	--loader '\EFI\ARCHX64\linux-hardened.efi'
